name: reverse-proxy

services:
  reverse-proxy-app:
    build:
      context: .
      dockerfile: DockerFile.dev
    command: npm run dev
    ports:
      - "8080:8080"
      - "80:80"
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    privileged: true  # ✅ Add this to allow full access to Docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock  
    depends_on:
      - redis-db

  redis-db:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
